title: Nimly Lock Control
views:
  - title: Front Door
    cards:
      - type: lock
        entity: lock.nimly_<your_ieee>
      - type: entities
        entities:
          - sensor.nimly_<your_ieee>_battery
